apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: student7
  name: student7-deployment
spec:
  selector:
    matchLabels:
      app: student7
  template:
    metadata:
      labels:
        app: student7
    spec:
      containers:
      - name: student7
        image: registry.tanzu.dk/ops2devops/student7:v1
