apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentx-deployment
  namespace: student7
spec:
  selector:
    matchLabels:
      app: student7
  template:
    metadata:
      labels:
        app: student7
    spec:
      containers:
      - name: student7
        image: registry.tanzu.dk/ops2devops/studentx:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student7
spec:
  type: NodePort
  selector:
    app: student7
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010 # Remember to change to student number.

